version: '3.1'

volumes:
  pg_sporttime:

services:
  pg_sporttime_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=2oo1Nurik
      - POSTGRES_DB=sporttime
    volumes:
      - pg_sporttime:/var/lib/postgresql/data
    ports:
      - "5432:5432"
